name: blockraft
description: A sample command-line application.
version: 1.0.0
repository: https://github.com/HorizonXDev/BlocKraft

environment:
  sdk: ^3.4.4

# Add regular dependencies here.
dependencies:
  archive: ^3.6.1
  args: ^2.5.0
  dart_console: ^4.1.0
  path: ^1.9.1
  yaml: ^3.1.2

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
